# Mirror Anti-Aliasing Fix v1.1.0
# Created by sonochiwa
# Source code: https://github.com/sonochiwa/sa-mirror-anti-aliasing-fix

[general]
isEnabled=1
logging=0
dumpPreviews=0

[antiAliasing]
supersample=2
